stages:
  - docker_image
  - build
  - deploy

variables:
    BUNDLE: "pitivi.flatpak"
    MANIFEST: build/flatpak/org.pitivi.Pitivi.json
    DBUS_ID: org.pitivi.Pitivi

build:
  image: registry.gitlab.gnome.org/gnome/pitivi:master-sdk_3.30
  stage: build
  artifacts:
    paths:
      - xunit.xml
  script:
    - export BUILDDIR=${HOME}/pitivi
    - export XUNIT_PATH=${CI_PROJECT_DIR}/xunit.xml
    - export MANIFEST=${BUILDDIR}/build/flatpak/org.pitivi.Pitivi.json
    - export RUN_IN_SANDBOX="flatpak-builder --filesystem=${BUILDDIR} --filesystem=${CI_PROJECT_DIR} --env=PITIVI_DEVELOPMENT=1 --run app ${MANIFEST}"

    # Working around the fact that flatpak-builder *requires* the cache dir
    # to be on the same filesystem as the build dir
    - export FLATPAK_BUILDER_CACHE="--state-dir=${HOME}/flatpak-cache"
    - mv ${CI_PROJECT_DIR} ${BUILDDIR}
    - mkdir -p ${CI_PROJECT_DIR}

    - cd ${BUILDDIR}
    - flatpak-builder ${FLATPAK_BUILDER_CACHE} --ccache --repo=repo --force-clean app build/flatpak/org.pitivi.Pitivi.json
    - ${RUN_IN_SANDBOX} meson mesonbuild/
    - ${RUN_IN_SANDBOX} ninja -C mesonbuild/
    - xvfb-run -n 32 -s "-screen 0 640x480x24" ${RUN_IN_SANDBOX} gst-validate-launcher $PWD/tests/ptv_testsuite.py --dump-on-failure --timeout-factor 4 --xunit-file ${XUNIT_PATH}

    - flatpak build-bundle --disable-rofiles-fuse repo ${BUNDLE} --runtime-repo=${RUNTIME} ${DBUS_ID} ${BRANCH}
  cache:
    paths:
    - flatpak-cache
  artifacts:
    paths:
    - ${BUNDLE}
    expire_in: 30 days

deploy:
  tags:
    - PitiviBuildMachine
  stage: deploy
  script:
    - flatpak build-import-bundle repo ${BUNDLE}

.build_emplate: &build_docker_image
    image: docker:latest
    services:
        - docker:dind
    script:
        # For debugging
        - echo ${BRANCH}
        - export IMAGE="${CI_REGISTRY}/${NAMESPACE}/${CI_PROJECT_NAME}:${BRANCH}-sdk_3.30"
        - echo ${IMAGE}
        - export BASE_IMAGE="registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:3.30"
        - echo ${BASE_IMAGE}
        - export TMPIMAGENAME="tmp-pitivi-${BRANCH}-sdk_3.30"
        - echo ${TMPIMAGENAME}

        # Not using a Dockerfile because we need the container to be privileged to run flatpak inside of it
        # and it is not possible to use a privileged `docker build`.
        - export RUN_IN_SANDBOX="flatpak-builder --filesystem=${BUILDDIR} --filesystem=${CI_PROJECT_DIR} --env=PITIVI_DEVELOPMENT=1 --run app ${MANIFEST}"

        - export BUILDDIR="\${HOME}/pitivi"
        - export CLONE_PITIVI="git clone ${CI_PROJECT_URL}.git --single-branch \${HOME}/pitivi -b ${CI_COMMIT_REF_NAME}"

        - export BUILD_PITIVI="flatpak-builder ${BUILDDIR}/app ${BUILDDIR}/build/flatpak/org.pitivi.Pitivi.json --state-dir=\${HOME}/flatpak-cache --ccache"

        - docker run --privileged --name ${TMPIMAGENAME} ${BASE_IMAGE} bash -c "${CLONE_PITIVI} && ${BUILD_PITIVI} && rm -Rf ${BUILDDIR}"
        - docker commit ${TMPIMAGENAME} ${IMAGE}
        - docker rm ${TMPIMAGENAME}
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker push ${IMAGE}
    only:
        - triggers
        - schedules
    retry: 1

pitivi:master:
    stage: docker_image
    before_script:
        # https://stackoverflow.com/questions/2264428/converting-string-to-lower-case-in-bash#2264537
        - export NAMESPACE="$(echo "${CI_PROJECT_NAMESPACE}" | tr A-Z a-z)"
        - export BRANCH=master
    <<: *build_docker_image

pitivi:1.0:
    stage: docker_image
    before_script:
        # https://stackoverflow.com/questions/2264428/converting-string-to-lower-case-in-bash#2264537
        - export BRANCH=1.0
        - export NAMESPACE="$(echo "${CI_PROJECT_NAMESPACE}" | tr A-Z a-z)"
    <<: *build_docker_image
