image: thiblahute/pitivi-ci


stages:
  - build
  - test

build:
  stage: build
  cache:
    paths:
      - .flatpak-builder/
  script:
    - ls -a
    - export
    - mkdir -p ~/.ccache/ && touch ~/.ccache/ccache.conf
    - flatpak-builder --force-clean app build/flatpak/org.pitivi.Pitivi.json --ccache
    - flatpak-builder --run app build/flatpak/org.pitivi.Pitivi.json meson mesonbuild/
    - flatpak-builder --run app build/flatpak/org.pitivi.Pitivi.json ninja -C mesonbuild/
    - xvfb-run  -n 32 -s "-screen 0 640x480x24" flatpak-builder --env=PITIVI_DEVELOPMENT=1 --run app build/flatpak/org.pitivi.Pitivi.json gst-validate-launcher $PWD/tests/ptv_testsuite.py --dump-on-failure --timeout-factor 4