stages:
  - build
  - deploy

variables:
  DBUS_ID: org.pitivi.Pitivi
  XUNIT_PATH: ${CI_PROJECT_DIR}/xunit.xml

build:
  image: registry.gitlab.gnome.org/gnome/pitivi:1.0-sdk_3.30
  stage: build
  artifacts:
    paths:
      - xunit.xml
  script:
    - export BUILDDIR=${HOME}/pitivi
    - export MANIFEST=${BUILDDIR}/build/flatpak/org.pitivi.Pitivi.json
    - export RUN_IN_SANDBOX="flatpak-builder --filesystem=${BUILDDIR} --filesystem=${CI_PROJECT_DIR} --env=PITIVI_DEVELOPMENT=1 --run app ${MANIFEST}"

    # Working around the fact that flatpak-builder *requires* the cache dir
    # to be on the same filesystem as the build dir
    - export FLATPAK_BUILDER_CACHE="--state-dir=${HOME}/flatpak-cache"
    - mv ${CI_PROJECT_DIR} ${BUILDDIR}
    - mkdir -p ${CI_PROJECT_DIR}

    - cd ${BUILDDIR}
    - flatpak-builder ${FLATPAK_BUILDER_CACHE} --ccache --repo=${CI_PROJECT_DIR}/repo --force-clean app build/flatpak/org.pitivi.Pitivi.json --subject="Rolling update for pitivi 1.0" --body="See ${CI_JOB_URL}"
    - ${RUN_IN_SANDBOX} meson mesonbuild/
    - ${RUN_IN_SANDBOX} ninja -C mesonbuild/
    - xvfb-run -n 32 -s "-screen 0 640x480x24" ${RUN_IN_SANDBOX} gst-validate-launcher $PWD/tests/ptv_testsuite.py --dump-on-failure --timeout-factor 4 --xunit-file ${XUNIT_PATH} --logs-dir=${CI_PROJECT_DIR}/tests-logs
  cache:
    paths:
    - flatpak-cache
  artifacts:
    expire_in: 30 days
    paths:
    - repo/
    - tests-logs/
    reports:
      junit:
        - ${XUNIT_PATH}

deploy:
  tags:
    - PitiviBuildMachine
  stage: deploy
  script:
    - flatpak build-commit-from --src-repo=repo /srv/http --timestamp=NOW --gpg-sign=739E841A
  only:
    - master@GNOME/pitivi
    - 1.0@GNOME/pitivi
    - thiblahute/sdk3.30_1.0@GNOME/pitivi
